export const ALL_PRODUCT_REQUEST = "ALL_PROUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS = "ALL_PROUCT_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PROUCT_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PROUCT__DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PROUCT__DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PROUCT__DETAILS_FAIL";



export const CLEAR_ERRORS = "CLEAR_ERRORS"; 