export const ALL_PRODUCT_REQUEST = "ALL_PROUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS = "ALL_PROUCT_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PROUCT_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PROUCT__DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PROUCT__DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PROUCT__DETAILS_FAIL";

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";





export const CLEAR_ERRORS = "CLEAR_ERRORS"; 